[build]
  publish = "build"
  command = "npm run build"
  functions = "functions"

[template.environment]
  NETLIFY_OAUTH_CLIENT_ID = "Your Netlify OAuth Client ID"
  NETLIFY_OAUTH_CLIENT_SECRET= "Your Netlify OAuth Client Secret"
